### ISSUE TITLE
求问下，8750h版10.14.4想升10.15步骤

### ISSUE THREAD

**Issue by xiaominglei001** [EngLearnsh/Soarsea-i9-8950HK-Hackintosh#1]
目前情况
```
系统10.14.4, cpu 8750h ，英睿达2666 8g ，ssd intel 760p ，无线网卡和蓝牙都是买时自带的，不用
```
目前用的EFI是https://github.com/kkzzhizhou/S200H_I7-8750H_Hackintosh   这个，我想升级到10.15，直接升级不行，会出现一个圆圈加个斜杠，问下怎么办，直接用你和这个EFI文件替换我现在的系统EFI然后再appstore升级系统就可以吗

**Comment by xiaominglei001** [comment]
也试了用你这个EFI直接替换我原来的，还是不行

**Comment by cxlanyagege** [comment]
你clover勾选verbose，然后把在禁行前最后那句话给我看一下

**Comment by xiaominglei001** [comment]
记得应该是busy time appleapcicpu之类的，我用时间机器恢复了系统，不敢再用系统appstore直接升级了，我用黑果小兵的10.15重新写了u盘，想从新安装，但是老是连安装界面都进不去，输出一段字就黑屏了

**Comment by xiaominglei001** [comment]
已用上10.15，说下我的步骤，黑果小兵上下载10.15系统，然后用balenaEtcher刻录好u盘，然后挂载这个u盘下的EFI分区，删除这个分区里的所有文件，然后用你这个EFI文件，全部拷贝到刚才刻录u盘的EFI分区里，然后正常安装就可以了。小白一个，只会用这个简单的方式了，多谢提供的EFI！

**Comment by xiaominglei001** [comment]
对了，另外还想问下，淘宝直接搜bcm943602CS这个网卡插上就可以用了吗，我现在没有可用的无线网卡了，原来10.14的usb网卡不可用，想买个bcm943602CS，能推荐个店家嘛

**Comment by cxlanyagege** [comment]
抱歉，这几天学校里有点忙，busy cpu有可能是fakesmc或者virtualsmc的问题，不过你现在升级好了倒也没关系了，2cs最开始我是给我的小米笔记本买的，但我买的那家店现在只有cs2了。[https://item.taobao.com/item.htm?spm=a1z10.1-c.w4004-660199089.2.36015ac5zvH5ns&id=532197802538](url)

**Comment by xiaominglei001** [comment]
这个cs2网卡一样用的吗？拔下自带的网卡插上就可以了吗？

**Comment by cxlanyagege** [comment]
我上面那个是key m的，当时用在笔记本上，只能插在放ssd的m2插槽上的，插原生网卡槽的要买key a+e的转接板，淘宝搜索bcm943602cs keya+e，第一家店铺的就可以

**Comment by xiaominglei001** [comment]
好的，多谢，我现在用bcm94360cs2加转接板插原生网卡槽了，免驱，很好用了

**Comment by cxlanyagege** [comment]
嗯，用上了就好
