### ISSUE TITLE
缺少一个apfs.efi,可能会导致融合硬盘下clover无法找到引导

### ISSUE THREAD

**Issue by talkmbbs** [EngLearnsh/Soarsea-i9-8950HK-Hackintosh#2]
尝试在融合硬盘下安装，会导致clover无法找到引导，一直黑屏。
在添加了apfs. efi后问题得到解决。
不知道是不是个例，就是反馈一下下。。。

**Comment by cxlanyagege** [comment]
没有融合盘，所以我也不是很清楚。。。

理论上，ApfsDriverLoader.efi+Aptio可以完全代替apfs.efi，并且不受os版本限制

**Comment by cxlanyagege** [comment]
老哥，我更新了ApfsLoader.efi，能麻烦测试下能否引导融合盘吗/不胜感激

**Comment by talkmbbs** [comment]
抱歉，最近有点忙，刚才测试了下，没有成功，还是需要加载apfs.efi才能进入系统，也可能是我的个例吧。

**Comment by cxlanyagege** [comment]
好吧。。。抱歉麻烦你了

**Comment by cxlanyagege** [comment]
好吧。。。抱歉麻烦你了
