### ISSUE TITLE
试了多个版本，说下各个版本的问题

### ISSUE THREAD

**Issue by MekaYangyi** [EngLearnsh/Soarsea-i9-8950HK-Hackintosh#4]
> > 有可能是fb上的问题
> > 之前有一次有位老哥说他的4k显示器到不了4k分辨率，我直接把fb除接口定义外的内容全部删除了，直接使用原生的intelgfx和bios驱动显示器。你可以试下用hackintool给fb打个补丁。因为最近放假了，暂时测试不了，实在抱歉
> 
> 我这是HDMI接4k识别不了，只能1080p，有啥办法？

你试一下最新的efi，mdp和hdmi都是可以用4k的

_Originally posted by @EngLearnsh in https://github.com/EngLearnsh/S200H-NUC-Hackintosh/issues/3#issuecomment-568888229_

机器是i7 8750h，没有安装无线网卡。
系统macOS Catalina

v1.1稳定，没有4k
v1.2b1稳定，4k没有测试
v1.2b2能够启动，插网线没有网络。
v1.2无法启动

**Comment by cxlanyagege** [comment]
v1.2开机时候勾下verbose，我看看是在哪一步卡住了

**Comment by cxlanyagege** [comment]
以太网的话，因为从1.0开始我没动过有线的驱动，当时刚买好的时候测试没问题。看一下系统报告里面有没有识别到有线网卡，有的话一般重置网络配置文件就行了

**Comment by MekaYangyi** [comment]
> verbose

选了verbose，命令行在这个位置卡主比较长时间，然后结束。

**Comment by MekaYangyi** [comment]
![微信图片_20191226003301](https://user-images.githubusercontent.com/20621802/71448491-69edb900-2777-11ea-95fd-b559ed7638b9.jpg)

仔细看了看，没看出什么，命令还在这个位置卡主比较长时间然后结束。

进入到苹果引导条界面，进度一直0%，强制重启后进度可以前进到80%，之后卡主，显示器闪烁一下继续卡主。

**Comment by MekaYangyi** [comment]
v1.2b2 以太网卡未识别出来

**Comment by cxlanyagege** [comment]
是驱动都没识别到？

**Comment by cxlanyagege** [comment]
找到问题了，有可能是kext里的plist文件LF和CRLF的问题，我重新修正后发了1.2.1，兄弟有空了试试启动和有线网是不是都ok了？
