### ISSUE TITLE
10.15.4 最新efi hdmi进度条闪一下黑屏y

### ISSUE THREAD

**Issue by imagine243** [EngLearnsh/Soarsea-i9-8950HK-Hackintosh#7]
i7 8850
抹盘安装的10.15.4
hdmi 接显示器 
使用最新的efi后， 启动loading时闪一下， 然后黑屏显示器自动关闭。

**Comment by cxlanyagege** [comment]
用mdp连接显示器有这个问题吗

**Comment by imagine243** [comment]
mbp 是可以的

**Comment by imagine243** [comment]
mbp 没有问题

**Comment by xlighting2017** [comment]
拔插一次 就好...

**Comment by 94fzb** [comment]
@imagine243 使用 WhateverGreen.kext 1.3.8 后就没有这个问题了

**Comment by cxlanyagege** [comment]
确实是whatevergreen的问题，更新到最新版就可以了
